In [1]:
#Importamos las librerias pandas, numpy y matplotlib respectivamente
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#Carga desde un archivo .xlsx sin indice
data = pd.read_excel('SDC.xlsx')
data.head(5)

,Ventas,Unnamed: 1,12,7,8,13,6,21,17,17.1,...,38,30.2,41.1,41.2,35,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Indicador,"Enero, 24","Febrero, 24","Marzo, 24","Abril, 24","Mayo, 24","Junio, 24","Julio, 24","Agosto, 24","Septiembre, 24",...,"Marzo, 26","Abril, 26","Mayo,26","Junio, 26","Julio,26",Total 2024,Total 2025,Total 2026,NaN,NaN
2,Generadas,5,6,11,23,26,43,55,36,56,...,85,74,95,82,32,519,1178,450,1697.0,0.392457
3,Aprobadas,1,2,7,14,8,13,30,19,26,...,41,42,44,35,12,215,451,201,666.0,0.509009
4,Condicionadas,0,0,1,0,4,0,3,0,1,...,14,16,17,10,9,100,287,102,387.0,NaN

In [3]:
data1= pd.read_excel('SDC.xlsx', skiprows=2)
data1.head(5)

,Indicador,"Enero, 24","Febrero, 24","Marzo, 24","Abril, 24","Mayo, 24","Junio, 24","Julio, 24","Agosto, 24","Septiembre, 24",...,"Marzo, 26","Abril, 26","Mayo,26","Junio, 26","Julio,26",Total 2024,Total 2025,Total 2026,Unnamed: 35,Unnamed: 36
0,Generadas,5,6,11,23,26,43,55,36,56,...,85,74,95,82,32,519,1178,450.0,1697.0,0.392457
1,Aprobadas,1,2,7,14,8,13,30,19,26,...,41,42,44,35,12,215,451,201.0,666.0,0.509009
2,Condicionadas,0,0,1,0,4,0,3,0,1,...,14,16,17,10,9,100,287,102.0,387.0,NaN
3,Rechazadas,4,4,4,9,14,22,17,13,13,...,30,16,30,33,9,163,392,137.0,555.0,NaN
4,Formalizadas,1,1,5,11,3,6,17,9,7,...,18,16,19,13,4,105,234,91.0,339.0,NaN

In [4]:
#Identificar valores nulos por columna
valores_nulos=data1.isnull().sum()
valores_nulos

Indicador           9
Enero, 24          20
Febrero, 24        20
Marzo, 24          20
Abril, 24          20
Mayo, 24           20
Junio, 24          20
Julio, 24          20
Agosto, 24         20
Septiembre, 24     21
Octubre, 24        20
Noviembre, 24      21
Diciembre, 25      21
Enero, 25          21
Febrero, 25        21
Marzo, 25          21
Abril, 25          21
Mayo, 25           15
Junio, 25          16
Julio, 25          15
Agosto, 25         17
Septiembre, 25     13
Octubre, 25        17
Noviembre, 25      16
Diciembre, 25.1    20
Enero, 26          16
Febrero, 26        17
Marzo, 26          16
Abril, 26          19
Mayo,26            17
Junio, 26          17
Julio,26           26
Total 2024         10
Total 2025         19
Total 2026         35
Unnamed: 35        37
Unnamed: 36        40
dtype: int64

In [5]:
#Primer filtro para obtener solamente infromación de ventas
ventas = data1.iloc[0:7, :]
ventas.to_csv('ventas.csv', index=False)
ventas.head(5)

,Indicador,"Enero, 24","Febrero, 24","Marzo, 24","Abril, 24","Mayo, 24","Junio, 24","Julio, 24","Agosto, 24","Septiembre, 24",...,"Marzo, 26","Abril, 26","Mayo,26","Junio, 26","Julio,26",Total 2024,Total 2025,Total 2026,Unnamed: 35,Unnamed: 36
0,Generadas,5,6,11,23,26,43,55,36,56,...,85,74,95,82,32,519,1178,450.0,1697.0,0.392457
1,Aprobadas,1,2,7,14,8,13,30,19,26,...,41,42,44,35,12,215,451,201.0,666.0,0.509009
2,Condicionadas,0,0,1,0,4,0,3,0,1,...,14,16,17,10,9,100,287,102.0,387.0,NaN
3,Rechazadas,4,4,4,9,14,22,17,13,13,...,30,16,30,33,9,163,392,137.0,555.0,NaN
4,Formalizadas,1,1,5,11,3,6,17,9,7,...,18,16,19,13,4,105,234,91.0,339.0,NaN

In [6]:
#Segundo filtro para obtener solamente información de financiera
financiera = data1.iloc[13:26, :]
financiera.to_csv('financiera.csv', index=False)
financiera.head(5)

,Indicador,"Enero, 24","Febrero, 24","Marzo, 24","Abril, 24","Mayo, 24","Junio, 24","Julio, 24","Agosto, 24","Septiembre, 24",...,"Marzo, 26","Abril, 26","Mayo,26","Junio, 26","Julio,26",Total 2024,Total 2025,Total 2026,Unnamed: 35,Unnamed: 36
13,ABC,-,-,-,-,-,-,-,-,-,...,NaN,NaN,NaN,NaN,NaN,1,0.000518,NaN,NaN,NaN
14,Afirme,-,-,-,-,-,-,-,-,18,...,NaN,NaN,NaN,NaN,NaN,121,0.062727,NaN,NaN,NaN
15,Banorte,-,-,-,-,-,-,-,-,1,...,33,33,34,15,10,790,0.409539,NaN,NaN,NaN
16,BBVA,-,-,-,-,-,-,-,-,12,...,12,7,11,16,3,202,0.104717,NaN,NaN,NaN
17,Ensueño,-,-,-,-,-,-,-,-,-,...,3,1,8,8,7,144,0.07465,NaN,NaN,NaN

In [7]:
#Tercer filtro para obtener solamente información de motivos no autorizadas
motivos_NoAutorizadas = data1.iloc[30:33, :]
motivos_NoAutorizadas.to_csv('motivos_NoAutorizadas.csv', index=False)
motivos_NoAutorizadas.head(5)

,Indicador,"Enero, 24","Febrero, 24","Marzo, 24","Abril, 24","Mayo, 24","Junio, 24","Julio, 24","Agosto, 24","Septiembre, 24",...,"Marzo, 26","Abril, 26","Mayo,26","Junio, 26","Julio,26",Total 2024,Total 2025,Total 2026,Unnamed: 35,Unnamed: 36
30,Mal Buro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,15,12,12,22,NaN,311,NaN,NaN,NaN,NaN
31,Score bajo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10,4,10,4,NaN,66,NaN,NaN,NaN,NaN
32,Capacidad de pago,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3,NaN,6,6,NaN,17,NaN,NaN,NaN,NaN

In [8]:
#Cuarto filtro para obtener solamente información de motivos no formalizadas
motivos_NoFormalizadas = data1.iloc[38:42, :]
motivos_NoFormalizadas.to_csv('motivos_NoFormalizadas.csv', index=False)
motivos_NoFormalizadas.head(5)

,Indicador,"Enero, 24","Febrero, 24","Marzo, 24","Abril, 24","Mayo, 24","Junio, 24","Julio, 24","Agosto, 24","Septiembre, 24",...,"Marzo, 26","Abril, 26","Mayo,26","Junio, 26","Julio,26",Total 2024,Total 2025,Total 2026,Unnamed: 35,Unnamed: 36
38,Compra en otro lado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1,2,2,2,NaN,44,NaN,NaN,NaN,NaN
39,Falta importe para enganche,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,3,1,2,NaN,6,NaN,NaN,NaN,NaN
40,Espera comprar en futuro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4,10,1,7,NaN,41,NaN,NaN,NaN,NaN
41,Otros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11,3,9,5,NaN,41,NaN,NaN,NaN,NaN

In [9]:
#Creación de un nuevo dataframe con los datos de ventas
data3 = ventas.isnull().sum()
data3

Indicador          1
Enero, 24          1
Febrero, 24        1
Marzo, 24          1
Abril, 24          1
Mayo, 24           1
Junio, 24          1
Julio, 24          1
Agosto, 24         1
Septiembre, 24     1
Octubre, 24        1
Noviembre, 24      1
Diciembre, 25      1
Enero, 25          1
Febrero, 25        1
Marzo, 25          1
Abril, 25          1
Mayo, 25           1
Junio, 25          1
Julio, 25          1
Agosto, 25         1
Septiembre, 25     1
Octubre, 25        1
Noviembre, 25      1
Diciembre, 25.1    1
Enero, 26          1
Febrero, 26        1
Marzo, 26          1
Abril, 26          1
Mayo,26            1
Junio, 26          1
Julio,26           1
Total 2024         1
Total 2025         1
Total 2026         1
Unnamed: 35        2
Unnamed: 36        5
dtype: int64

In [10]:
#Corrección de valores nulos en la columna "Indicador" del dataframe ventas, reemplazando los valores nulos con "Sin dato"
ventas['Indicador'] = ventas['Indicador'].fillna("Sin dato")
data3=ventas.isnull().sum()
data3

Indicador          0
Enero, 24          1
Febrero, 24        1
Marzo, 24          1
Abril, 24          1
Mayo, 24           1
Junio, 24          1
Julio, 24          1
Agosto, 24         1
Septiembre, 24     1
Octubre, 24        1
Noviembre, 24      1
Diciembre, 25      1
Enero, 25          1
Febrero, 25        1
Marzo, 25          1
Abril, 25          1
Mayo, 25           1
Junio, 25          1
Julio, 25          1
Agosto, 25         1
Septiembre, 25     1
Octubre, 25        1
Noviembre, 25      1
Diciembre, 25.1    1
Enero, 26          1
Febrero, 26        1
Marzo, 26          1
Abril, 26          1
Mayo,26            1
Junio, 26          1
Julio,26           1
Total 2024         1
Total 2025         1
Total 2026         1
Unnamed: 35        2
Unnamed: 36        5
dtype: int64

In [11]:
ventas.columns

Index(['Indicador', 'Enero, 24', 'Febrero, 24', 'Marzo, 24', 'Abril, 24',
       'Mayo, 24', 'Junio, 24', 'Julio, 24', 'Agosto, 24', 'Septiembre, 24',
       'Octubre, 24', 'Noviembre, 24', 'Diciembre, 25', 'Enero, 25',
       'Febrero, 25', 'Marzo, 25', 'Abril, 25', 'Mayo, 25', 'Junio, 25',
       'Julio, 25', 'Agosto, 25', 'Septiembre, 25', 'Octubre, 25',
       'Noviembre, 25', 'Diciembre, 25.1', 'Enero, 26', 'Febrero, 26',
       'Marzo, 26', 'Abril, 26', 'Mayo,26', 'Junio, 26', 'Julio,26',
       'Total 2024', 'Total 2025', 'Total 2026', 'Unnamed: 35', 'Unnamed: 36'],
      dtype='str')

In [12]:
#Corrección de valores nulos en las columnas de ventas, reemplazando los valores nulos con 0
ventas[['Enero, 24', 'Febrero, 24', 'Marzo, 24', 'Abril, 24',
       'Mayo, 24', 'Junio, 24', 'Julio, 24', 'Agosto, 24', 'Septiembre, 24',
       'Octubre, 24', 'Noviembre, 24', 'Diciembre, 25', 'Enero, 25',
       'Febrero, 25', 'Marzo, 25', 'Abril, 25', 'Mayo, 25', 'Junio, 25',
       'Julio, 25', 'Agosto, 25', 'Septiembre, 25', 'Octubre, 25',
       'Noviembre, 25', 'Diciembre, 25.1', 'Enero, 26', 'Febrero, 26',
       'Marzo, 26', 'Abril, 26', 'Mayo,26', 'Junio, 26', 'Julio,26',
       'Total 2024', 'Total 2025', 'Total 2026', 'Unnamed: 35', 'Unnamed: 36']]= ventas[['Enero, 24', 'Febrero, 24', 'Marzo, 24', 'Abril, 24',
       'Mayo, 24', 'Junio, 24', 'Julio, 24', 'Agosto, 24', 'Septiembre, 24',
       'Octubre, 24', 'Noviembre, 24', 'Diciembre, 25', 'Enero, 25',
       'Febrero, 25', 'Marzo, 25', 'Abril, 25', 'Mayo, 25', 'Junio, 25',
       'Julio, 25', 'Agosto, 25', 'Septiembre, 25', 'Octubre, 25',
       'Noviembre, 25', 'Diciembre, 25.1', 'Enero, 26', 'Febrero, 26',
       'Marzo, 26', 'Abril, 26', 'Mayo,26', 'Junio, 26', 'Julio,26',
       'Total 2024', 'Total 2025', 'Total 2026', 'Unnamed: 35', 'Unnamed: 36']].fillna(0) 
data3=ventas.isnull().sum()
data3

Indicador          0
Enero, 24          0
Febrero, 24        0
Marzo, 24          0
Abril, 24          0
Mayo, 24           0
Junio, 24          0
Julio, 24          0
Agosto, 24         0
Septiembre, 24     0
Octubre, 24        0
Noviembre, 24      0
Diciembre, 25      0
Enero, 25          0
Febrero, 25        0
Marzo, 25          0
Abril, 25          0
Mayo, 25           0
Junio, 25          0
Julio, 25          0
Agosto, 25         0
Septiembre, 25     0
Octubre, 25        0
Noviembre, 25      0
Diciembre, 25.1    0
Enero, 26          0
Febrero, 26        0
Marzo, 26          0
Abril, 26          0
Mayo,26            0
Junio, 26          0
Julio,26           0
Total 2024         0
Total 2025         0
Total 2026         0
Unnamed: 35        0
Unnamed: 36        0
dtype: int64

In [13]:
#Identificar valores nulos por columna en el dataframe financiera y creación de un nuevo dataframe con los datos de financiera
data4 = financiera.isnull().sum()
data4

Indicador           0
Enero, 24           1
Febrero, 24         1
Marzo, 24           1
Abril, 24           1
Mayo, 24            1
Junio, 24           1
Julio, 24           1
Agosto, 24          1
Septiembre, 24      2
Octubre, 24         1
Noviembre, 24       2
Diciembre, 25       2
Enero, 25           2
Febrero, 25         2
Marzo, 25           2
Abril, 25           2
Mayo, 25            1
Junio, 25           4
Julio, 25           2
Agosto, 25          1
Septiembre, 25      1
Octubre, 25         5
Noviembre, 25       5
Diciembre, 25.1     7
Enero, 26           5
Febrero, 26         6
Marzo, 26           5
Abril, 26           7
Mayo,26             7
Junio, 26           7
Julio,26            7
Total 2024          0
Total 2025          0
Total 2026         13
Unnamed: 35        13
Unnamed: 36        13
dtype: int64

In [14]:
financiera.columns

Index(['Indicador', 'Enero, 24', 'Febrero, 24', 'Marzo, 24', 'Abril, 24',
       'Mayo, 24', 'Junio, 24', 'Julio, 24', 'Agosto, 24', 'Septiembre, 24',
       'Octubre, 24', 'Noviembre, 24', 'Diciembre, 25', 'Enero, 25',
       'Febrero, 25', 'Marzo, 25', 'Abril, 25', 'Mayo, 25', 'Junio, 25',
       'Julio, 25', 'Agosto, 25', 'Septiembre, 25', 'Octubre, 25',
       'Noviembre, 25', 'Diciembre, 25.1', 'Enero, 26', 'Febrero, 26',
       'Marzo, 26', 'Abril, 26', 'Mayo,26', 'Junio, 26', 'Julio,26',
       'Total 2024', 'Total 2025', 'Total 2026', 'Unnamed: 35', 'Unnamed: 36'],
      dtype='str')

In [16]:
#Llenado de valores nulos en las columnas de financiera, reemplazando los valores nulos con 0
financiera[['Enero, 24', 'Febrero, 24', 'Marzo, 24', 'Abril, 24',
       'Mayo, 24', 'Junio, 24', 'Julio, 24', 'Agosto, 24', 'Septiembre, 24',
       'Octubre, 24', 'Noviembre, 24', 'Diciembre, 25', 'Enero, 25',
       'Febrero, 25', 'Marzo, 25', 'Abril, 25', 'Mayo, 25', 'Junio, 25',
       'Julio, 25', 'Agosto, 25', 'Septiembre, 25', 'Octubre, 25',
       'Noviembre, 25', 'Diciembre, 25.1', 'Enero, 26', 'Febrero, 26',
       'Marzo, 26', 'Abril, 26', 'Mayo,26', 'Junio, 26', 'Julio,26',
       'Total 2024', 'Total 2025', 'Total 2026', 'Unnamed: 35', 'Unnamed: 36']]= financiera[['Enero, 24', 'Febrero, 24', 'Marzo, 24', 'Abril, 24',
       'Mayo, 24', 'Junio, 24', 'Julio, 24', 'Agosto, 24', 'Septiembre, 24',
       'Octubre, 24', 'Noviembre, 24', 'Diciembre, 25', 'Enero, 25',
       'Febrero, 25', 'Marzo, 25', 'Abril, 25', 'Mayo, 25', 'Junio, 25',
       'Julio, 25', 'Agosto, 25', 'Septiembre, 25', 'Octubre, 25',
       'Noviembre, 25', 'Diciembre, 25.1', 'Enero, 26', 'Febrero, 26',
       'Marzo, 26', 'Abril, 26', 'Mayo,26', 'Junio, 26', 'Julio,26',
       'Total 2024', 'Total 2025', 'Total 2026', 'Unnamed: 35', 'Unnamed: 36']].fillna(0) 
data4=financiera.isnull().sum()
data4

Indicador          0
Enero, 24          0
Febrero, 24        0
Marzo, 24          0
Abril, 24          0
Mayo, 24           0
Junio, 24          0
Julio, 24          0
Agosto, 24         0
Septiembre, 24     0
Octubre, 24        0
Noviembre, 24      0
Diciembre, 25      0
Enero, 25          0
Febrero, 25        0
Marzo, 25          0
Abril, 25          0
Mayo, 25           0
Junio, 25          0
Julio, 25          0
Agosto, 25         0
Septiembre, 25     0
Octubre, 25        0
Noviembre, 25      0
Diciembre, 25.1    0
Enero, 26          0
Febrero, 26        0
Marzo, 26          0
Abril, 26          0
Mayo,26            0
Junio, 26          0
Julio,26           0
Total 2024         0
Total 2025         0
Total 2026         0
Unnamed: 35        0
Unnamed: 36        0
dtype: int64

In [17]:
motivos_NoAutorizadas.columns

Index(['Indicador', 'Enero, 24', 'Febrero, 24', 'Marzo, 24', 'Abril, 24',
       'Mayo, 24', 'Junio, 24', 'Julio, 24', 'Agosto, 24', 'Septiembre, 24',
       'Octubre, 24', 'Noviembre, 24', 'Diciembre, 25', 'Enero, 25',
       'Febrero, 25', 'Marzo, 25', 'Abril, 25', 'Mayo, 25', 'Junio, 25',
       'Julio, 25', 'Agosto, 25', 'Septiembre, 25', 'Octubre, 25',
       'Noviembre, 25', 'Diciembre, 25.1', 'Enero, 26', 'Febrero, 26',
       'Marzo, 26', 'Abril, 26', 'Mayo,26', 'Junio, 26', 'Julio,26',
       'Total 2024', 'Total 2025', 'Total 2026', 'Unnamed: 35', 'Unnamed: 36'],
      dtype='str')

In [18]:
#Identificar valores nulos por columna en el dataframe motivos_NoAutorizadas y creación de un nuevo dataframe con los datos de motivos_NoAutorizadas
data5 = motivos_NoAutorizadas.isnull().sum()
data5

Indicador          0
Enero, 24          3
Febrero, 24        3
Marzo, 24          3
Abril, 24          3
Mayo, 24           3
Junio, 24          3
Julio, 24          3
Agosto, 24         3
Septiembre, 24     3
Octubre, 24        3
Noviembre, 24      3
Diciembre, 25      3
Enero, 25          3
Febrero, 25        3
Marzo, 25          3
Abril, 25          3
Mayo, 25           1
Junio, 25          0
Julio, 25          1
Agosto, 25         1
Septiembre, 25     0
Octubre, 25        0
Noviembre, 25      0
Diciembre, 25.1    1
Enero, 26          0
Febrero, 26        0
Marzo, 26          0
Abril, 26          1
Mayo,26            0
Junio, 26          0
Julio,26           3
Total 2024         0
Total 2025         3
Total 2026         3
Unnamed: 35        3
Unnamed: 36        3
dtype: int64

In [19]:
#Corrección de valores nulos en las columnas de motivos_NoAutorizadas, reemplazando los valores nulos con 0
motivos_NoAutorizadas[['Enero, 24', 'Febrero, 24', 'Marzo, 24', 'Abril, 24',
       'Mayo, 24', 'Junio, 24', 'Julio, 24', 'Agosto, 24', 'Septiembre, 24',
       'Octubre, 24', 'Noviembre, 24', 'Diciembre, 25', 'Enero, 25',
       'Febrero, 25', 'Marzo, 25', 'Abril, 25', 'Mayo, 25', 'Junio, 25',
       'Julio, 25', 'Agosto, 25', 'Septiembre, 25', 'Octubre, 25',
       'Noviembre, 25', 'Diciembre, 25.1', 'Enero, 26', 'Febrero, 26',
       'Marzo, 26', 'Abril, 26', 'Mayo,26', 'Junio, 26', 'Julio,26',
       'Total 2024', 'Total 2025', 'Total 2026', 'Unnamed: 35', 'Unnamed: 36']]= motivos_NoAutorizadas[['Enero, 24', 'Febrero, 24', 'Marzo, 24', 'Abril, 24',
       'Mayo, 24', 'Junio, 24', 'Julio, 24', 'Agosto, 24', 'Septiembre, 24',
       'Octubre, 24', 'Noviembre, 24', 'Diciembre, 25', 'Enero, 25',
       'Febrero, 25', 'Marzo, 25', 'Abril, 25', 'Mayo, 25', 'Junio, 25',
       'Julio, 25', 'Agosto, 25', 'Septiembre, 25', 'Octubre, 25',
       'Noviembre, 25', 'Diciembre, 25.1', 'Enero, 26', 'Febrero, 26',
       'Marzo, 26', 'Abril, 26', 'Mayo,26', 'Junio, 26', 'Julio,26',
       'Total 2024', 'Total 2025', 'Total 2026', 'Unnamed: 35', 'Unnamed: 36']].fillna(0) 
data5=motivos_NoAutorizadas.isnull().sum()
data5

Indicador          0
Enero, 24          0
Febrero, 24        0
Marzo, 24          0
Abril, 24          0
Mayo, 24           0
Junio, 24          0
Julio, 24          0
Agosto, 24         0
Septiembre, 24     0
Octubre, 24        0
Noviembre, 24      0
Diciembre, 25      0
Enero, 25          0
Febrero, 25        0
Marzo, 25          0
Abril, 25          0
Mayo, 25           0
Junio, 25          0
Julio, 25          0
Agosto, 25         0
Septiembre, 25     0
Octubre, 25        0
Noviembre, 25      0
Diciembre, 25.1    0
Enero, 26          0
Febrero, 26        0
Marzo, 26          0
Abril, 26          0
Mayo,26            0
Junio, 26          0
Julio,26           0
Total 2024         0
Total 2025         0
Total 2026         0
Unnamed: 35        0
Unnamed: 36        0
dtype: int64

In [20]:
#Identificar valores nulos por columna en el dataframe motivos_NoFormalizadas y creación de un nuevo dataframe con los datos de motivos_NoFormalizadas
data6 = motivos_NoFormalizadas.isnull().sum()
data6

Indicador          0
Enero, 24          4
Febrero, 24        4
Marzo, 24          4
Abril, 24          4
Mayo, 24           4
Junio, 24          4
Julio, 24          4
Agosto, 24         4
Septiembre, 24     4
Octubre, 24        4
Noviembre, 24      4
Diciembre, 25      4
Enero, 25          4
Febrero, 25        4
Marzo, 25          4
Abril, 25          4
Mayo, 25           1
Junio, 25          1
Julio, 25          1
Agosto, 25         3
Septiembre, 25     0
Octubre, 25        0
Noviembre, 25      0
Diciembre, 25.1    0
Enero, 26          0
Febrero, 26        0
Marzo, 26          0
Abril, 26          0
Mayo,26            0
Junio, 26          0
Julio,26           4
Total 2024         0
Total 2025         4
Total 2026         4
Unnamed: 35        4
Unnamed: 36        4
dtype: int64

In [21]:
#Corrección de valores nulos en las columnas de motivos_NoFormalizadas, reemplazando los valores nulos con 0
motivos_NoFormalizadas[['Enero, 24', 'Febrero, 24', 'Marzo, 24', 'Abril, 24',
       'Mayo, 24', 'Junio, 24', 'Julio, 24', 'Agosto, 24', 'Septiembre, 24',
       'Octubre, 24', 'Noviembre, 24', 'Diciembre, 25', 'Enero, 25',
       'Febrero, 25', 'Marzo, 25', 'Abril, 25', 'Mayo, 25', 'Junio, 25',
       'Julio, 25', 'Agosto, 25', 'Septiembre, 25', 'Octubre, 25',
       'Noviembre, 25', 'Diciembre, 25.1', 'Enero, 26', 'Febrero, 26',
       'Marzo, 26', 'Abril, 26', 'Mayo,26', 'Junio, 26', 'Julio,26',
       'Total 2024', 'Total 2025', 'Total 2026', 'Unnamed: 35', 'Unnamed: 36']]= motivos_NoFormalizadas[['Enero, 24', 'Febrero, 24', 'Marzo, 24', 'Abril, 24',
       'Mayo, 24', 'Junio, 24', 'Julio, 24', 'Agosto, 24', 'Septiembre, 24',
       'Octubre, 24', 'Noviembre, 24', 'Diciembre, 25', 'Enero, 25',
       'Febrero, 25', 'Marzo, 25', 'Abril, 25', 'Mayo, 25', 'Junio, 25',
       'Julio, 25', 'Agosto, 25', 'Septiembre, 25', 'Octubre, 25',
       'Noviembre, 25', 'Diciembre, 25.1', 'Enero, 26', 'Febrero, 26',
       'Marzo, 26', 'Abril, 26', 'Mayo,26', 'Junio, 26', 'Julio,26',
       'Total 2024', 'Total 2025', 'Total 2026', 'Unnamed: 35', 'Unnamed: 36']].fillna(0) 
data6=motivos_NoFormalizadas.isnull().sum()
data6

Indicador          0
Enero, 24          0
Febrero, 24        0
Marzo, 24          0
Abril, 24          0
Mayo, 24           0
Junio, 24          0
Julio, 24          0
Agosto, 24         0
Septiembre, 24     0
Octubre, 24        0
Noviembre, 24      0
Diciembre, 25      0
Enero, 25          0
Febrero, 25        0
Marzo, 25          0
Abril, 25          0
Mayo, 25           0
Junio, 25          0
Julio, 25          0
Agosto, 25         0
Septiembre, 25     0
Octubre, 25        0
Noviembre, 25      0
Diciembre, 25.1    0
Enero, 26          0
Febrero, 26        0
Marzo, 26          0
Abril, 26          0
Mayo,26            0
Junio, 26          0
Julio,26           0
Total 2024         0
Total 2025         0
Total 2026         0
Unnamed: 35        0
Unnamed: 36        0
dtype: int64

In [22]:
ventas_sin_nulos = ventas
ventas_sin_nulos.to_csv('ventas_sin_nulos.csv', index=False)

In [23]:
financiera_sin_nulos = financiera
financiera_sin_nulos.to_csv('financiera_sin_nulos.csv', index=False)

In [24]:
motivos_NoAutorizadas_sin_nulos = motivos_NoAutorizadas
motivos_NoAutorizadas_sin_nulos.to_csv('motivos_NoAutorizadas_sin_nulos.csv', index=False)

In [25]:
motivos_NoFormalizadas_sin_nulos = motivos_NoFormalizadas
motivos_NoFormalizadas_sin_nulos.to_csv('motivos_NoFormalizadas_sin_nulos.csv', index=False)